const mongoose = require('mongoose');

const reminderSchema = new mongoose.Schema({
  patient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Patient',
    required: true,
    index: true
  },
  type: {
    type: String,
    enum: ['vitals_due', 'medication', 'appointment', 'custom'],
    required: true
  },
  title: {
    type: String,
    required: true
  },
  description: {
    type: String
  },
  dueDate: {
    type: Date,
    required: true
  },
  customTime: {
    type: String, // Format: "HH:MM" (24-hour)
    default: null
  },
  recurrence: {
    type: String,
    enum: ['none', 'daily', 'weekly', 'monthly'],
    default: 'none'
  },
  status: {
    type: String,
    enum: ['pending', 'snoozed', 'completed'],
    default: 'pending',
    index: true
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  },
  snoozedUntil: {
    type: Date
  },
  completedAt: {
    type: Date
  },
  completedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  autoGenerated: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

// Indexes for efficient querying
reminderSchema.index({ patient: 1, status: 1, dueDate: 1 });
reminderSchema.index({ status: 1, dueDate: 1 });
reminderSchema.index({ dueDate: 1, status: 1 });

module.exports = mongoose.model('Reminder', reminderSchema);
