const cron = require('node-cron');
const Reminder = require('../models/Reminder');
const Patient = require('../models/Patient');
const Vitals = require('../models/Vitals');
const User = require('../models/User');
const { sendReminderEmail } = require('./emailService');

// Check for patients who need vitals recorded every day at 8 AM
const checkVitalsDue = cron.schedule('0 8 * * *', async () => {
  try {
    console.log('Running vitals check scheduler...');
    
    const patients = await Patient.find({ active: true });
    const now = new Date();
    const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    
    for (const patient of patients) {
      // Check if vitals were recorded in last 24 hours
      const recentVitals = await Vitals.findOne({
        patient: patient._id,
        recordedAt: { $gte: yesterday }
      });
      
      if (!recentVitals) {
        // Check if reminder already exists
        const existingReminder = await Reminder.findOne({
          patient: patient._id,
          type: 'vitals_due',
          status: 'pending',
          dueDate: { $gte: yesterday }
        });
        
        if (!existingReminder) {
          // Create reminder
          const reminder = await Reminder.create({
            patient: patient._id,
            type: 'vitals_due',
            title: 'Vitals Recording Due',
            description: `Please record ${patient.template} vitals for ${patient.name}`,
            dueDate: now,
            priority: 'high',
            autoGenerated: true
          });
          
          console.log(`Created vitals reminder for patient: ${patient.name}`);
          
          // Send email to primary nurse if available
          if (patient.primaryNurse) {
            const nurse = await User.findById(patient.primaryNurse);
            if (nurse && nurse.email) {
              await sendReminderEmail({
                to: nurse.email,
                patient: patient,
                reminder: reminder
              });
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('Vitals check scheduler error:', error);
  }
}, {
  scheduled: false // Don't start automatically
});

// Auto-complete overdue reminders after 7 days
const cleanupReminders = cron.schedule('0 0 * * *', async () => {
  try {
    console.log('Running reminder cleanup...');
    
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    
    await Reminder.updateMany(
      {
        status: { $in: ['pending', 'snoozed'] },
        dueDate: { $lt: sevenDaysAgo }
      },
      {
        status: 'completed',
        completedAt: new Date()
      }
    );
    
    console.log('Reminder cleanup completed');
  } catch (error) {
    console.error('Reminder cleanup error:', error);
  }
}, {
  scheduled: false
});

const startSchedulers = () => {
  console.log('Starting reminder schedulers...');
  checkVitalsDue.start();
  cleanupReminders.start();
  console.log('Schedulers started successfully');
};

const stopSchedulers = () => {
  checkVitalsDue.stop();
  cleanupReminders.stop();
  console.log('Schedulers stopped');
};

module.exports = {
  startSchedulers,
  stopSchedulers,
  checkVitalsDue,
  cleanupReminders
};
