import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';

const RemindersPage = () => {
  const [reminders, setReminders] = useState([]);
  const [filter, setFilter] = useState('pending');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReminders();
  }, [filter]);

  const fetchReminders = async () => {
    try {
      setLoading(true);
      const params = filter === 'all' ? {} : { status: filter };
      
      const response = await api.get('/reminders', { params });
      if (response.data.success) {
        setReminders(response.data.data.reminders);
      }
    } catch (error) {
      console.error('Error fetching reminders:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSnooze = async (id) => {
    const hours = prompt('Snooze for how many hours? (1-72):');
    if (!hours || isNaN(hours) || hours < 1 || hours > 72) return;

    try {
      await api.put(`/reminders/${id}/snooze`, { hours: parseInt(hours) });
      fetchReminders();
    } catch (error) {
      console.error('Error snoozing reminder:', error);
      alert('Failed to snooze reminder');
    }
  };

  const handleComplete = async (id) => {
    try {
      await api.put(`/reminders/${id}/complete`);
      fetchReminders();
    } catch (error) {
      console.error('Error completing reminder:', error);
      alert('Failed to complete reminder');
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'high': return 'border-l-4 border-red-500';
      case 'medium': return 'border-l-4 border-yellow-500';
      case 'low': return 'border-l-4 border-blue-500';
      default: return '';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center space-x-8">
              <Link to="/dashboard" className="text-2xl font-bold text-primary-600">Manual-RPM</Link>
              <Link to="/patients" className="text-gray-600 hover:text-gray-900">Patients</Link>
              <Link to="/alerts" className="text-gray-600 hover:text-gray-900">Alerts</Link>
              <Link to="/reminders" className="text-gray-900 font-medium">Reminders</Link>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Reminders</h1>

        {/* Filter Tabs */}
        <div className="card mb-6">
          <div className="flex space-x-4">
            {['pending', 'snoozed', 'completed', 'all'].map((status) => (
              <button
                key={status}
                onClick={() => setFilter(status)}
                className={`px-4 py-2 rounded-lg font-medium ${
                  filter === status
                    ? 'bg-primary-600 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {status.charAt(0).toUpperCase() + status.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {/* Reminders List */}
        {loading ? (
          <div className="text-center py-12">Loading reminders...</div>
        ) : reminders.length === 0 ? (
          <div className="card text-center py-12">
            <p className="text-gray-600">No reminders found</p>
          </div>
        ) : (
          <div className="space-y-4">
            {reminders.map((reminder) => (
              <div key={reminder._id} className={`card ${getPriorityColor(reminder.priority)}`}>
                <div className="flex justify-between items-start">
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <span className="px-2 py-1 bg-gray-100 rounded text-xs font-semibold uppercase">
                        {reminder.type.replace('_', ' ')}
                      </span>
                      <span className="px-2 py-1 bg-gray-100 rounded text-xs font-semibold uppercase">
                        {reminder.priority}
                      </span>
                      {reminder.autoGenerated && (
                        <span className="px-2 py-1 bg-blue-100 text-blue-800 rounded text-xs font-semibold">
                          Auto
                        </span>
                      )}
                    </div>
                    <h3 className="font-semibold text-lg">{reminder.title}</h3>
                    {reminder.description && (
                      <p className="text-sm text-gray-600 mt-1">{reminder.description}</p>
                    )}
                    <div className="flex items-center space-x-4 mt-2 text-sm text-gray-600">
                      <Link to={`/patients/${reminder.patient._id}`} className="hover:underline">
                        {reminder.patient.name} (MRN: {reminder.patient.mrn})
                      </Link>
                      <span>Due: {new Date(reminder.dueDate).toLocaleString()}</span>
                      {reminder.snoozedUntil && (
                        <span className="text-yellow-600">
                          Snoozed until: {new Date(reminder.snoozedUntil).toLocaleString()}
                        </span>
                      )}
                    </div>
                  </div>
                  <div className="flex space-x-2">
                    {(reminder.status === 'pending' || reminder.status === 'snoozed') && (
                      <>
                        <button
                          onClick={() => handleSnooze(reminder._id)}
                          className="px-3 py-1 bg-yellow-100 text-yellow-700 rounded text-sm font-medium hover:bg-yellow-200"
                        >
                          Snooze
                        </button>
                        <button
                          onClick={() => handleComplete(reminder._id)}
                          className="px-3 py-1 bg-green-600 text-white rounded text-sm font-medium hover:bg-green-700"
                        >
                          Complete
                        </button>
                      </>
                    )}
                    {reminder.status === 'completed' && (
                      <span className="px-3 py-1 bg-green-100 text-green-800 rounded text-sm font-semibold">
                        ✓ Completed
                      </span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
};

export default RemindersPage;
